# list of environments to test
matrix:
  include:

    # Full tests (with online API)
    - os: linux
      language: python
      python: 3.9
      dist: xenial
      sudo: true
      env:
        - TO_TEST=TEST_FULL
    - os: osx
      language: generic
      python: ">=3.6"
      env:
        - TO_TEST=TEST_FULL
      before_install:
        - brew outdated python3 || brew install python3 || brew upgrade python3
        - python3 -m venv env
        - source env/bin/activate

    # Mock tests (with mock API)
    - os: linux
      language: python
      python: 3.6
      env:
        - TO_TEST=TEST_MOCK
    - os: linux
      language: python
      dist: xenial
      python: 3.7
      sudo: true
      env:
        - TO_TEST=TEST_MOCK
    - os: linux
      language: python
      dist: xenial
      python: 3.8
      sudo: true
      env:
        - TO_TEST=TEST_MOCK
    - os: linux
      language: python
      dist: xenial
      python: 3.9
      sudo: true
      env:
        - TO_TEST=TEST_MOCK


    # Install tests
    - os: linux
      language: python
      python: 2.7
      env:
        - TO_TEST=INSTALL
      if: type = cron
    - os: linux
      language: python
      dist: xenial
      sudo: true
      python: 3.9
      env:
        - TO_TEST=INSTALL
      if: type = cron
    - os: osx
      language: generic
      python: 2.7
      env:
        - TO_TEST=INSTALL
      if: type = cron
    - os: osx
      language: generic
      python: ">=3.6"
      env:
        - TO_TEST=INSTALL
      if: type = cron

  allow_failures:
    - python: 2.7

# command to run tests
script:
  - python --version
  - if [ "$TO_TEST" = "TEST_MOCK" ] ||
       [ "$TO_TEST" = "TEST_FULL" ]; then PUBS_TESTS_MODE=MOCK    python setup.py test; fi
  - if [ "$TO_TEST" = "TEST_FULL" ]; then PUBS_TESTS_MODE=COLLECT python setup.py test; fi
  - if [ "$TO_TEST" = "INSTALL" ]; then pip install -U pip && pip install pubs && pubs --help && pip uninstall -y pubs; fi
