# list of environments to test
matrix:
  include:
    - os: linux
      language: python
      python: 2.7
    - os: linux
      language: python
      python: 3.3
    - os: linux
      language: python
      python: 3.4
    - os: linux
      language: python
      python: 3.5
    - os: linux
      language: python
      python: 3.6
    - os: osx
      language: generic
      python: 2.7
      before_install:
        - python2 --version
        - pip2 install -U virtualenv
        - virtualenv env -p python2
        - source env/bin/activate
    - os: osx
      language: generic
      python: ">=3.6"
      before_install:
        - brew update
        - brew outdated python3 || brew install python3 || brew upgrade python3
        - python3 -m venv env
        - source env/bin/activate

# command to install dependencies
install:
    - python --version

# command to run tests
script: python setup.py test
